# Generated by Django 3.2.12 on 2022-02-24 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.CharField(max_length=10, unique=True)),
                ('professor_name', models.CharField(max_length=30)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professor_modules', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_username', models.CharField(max_length=20, unique=True)),
                ('student_email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('student_password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=4, unique=True)),
                ('module_name', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('module_professor', models.ManyToManyField(to='application.Professor')),
            ],
        ),
    ]
