# Generated by Django 3.2.12 on 2022-03-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20220317_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='professor_modules',
        ),
        migrations.AlterField(
            model_name='module',
            name='module_code',
            field=models.CharField(max_length=4),
        ),
    ]
