# Generated by Django 3.2.12 on 2022-03-22 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20220322_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_code',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
